Objects & DateTime Datatype

In [2]:
import pandas as pd

In [3]:

dates =['2026-10-04','2026-10-04','2026-10-04']
df =pd.DataFrame({'Date': dates})

In [4]:
df

         Date
0  2026-10-04
1  2026-10-04
2  2026-10-04

In [5]:
timestamps = pd.to_datetime(dates)

In [6]:
df2 = pd.DataFrame({'Date2': timestamps})

In [7]:
df2

       Date2
0 2026-10-04
1 2026-10-04
2 2026-10-04

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date2   3 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.0 bytes

In [9]:
fuel = pd.read_csv("fuel.csv")

In [10]:
fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   country                    22 non-null     object
 1   sub_region                 22 non-null     object
 2   iso3                       22 non-null     object
 3   gasoline_usd_per_liter     22 non-null     float64
 4   diesel_usd_per_liter       22 non-null     float64
 5   lpg_usd_per_kg             22 non-null     float64
 6   avg_monthly_income_usd     22 non-null     int64
 7   fuel_affordability_index   22 non-null     float64
 8   oil_import_dependency_pct  22 non-null     int64
 9   refinery_capacity_kbpd     22 non-null     int64
 10  ev_adoption_pct            22 non-null     float64
 11  fuel_subsidy_active        22 non-null     bool
 12  subsidy_cost_bn_usd        22 non-null     float64
 13  co2_transport_mt           22 non-null     float64
 14  price_date                 22 non-null     object
 15  gasoline_pct_daily_wage    22 non-null     float64
dtypes: bool(1), float64(8), int64(3), object(4)
memory usage: 2.7+ KB

In [11]:
fuel

,country,sub_region,iso3,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,South Asia,PAK,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,South Asia,IND,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,South Asia,BGD,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,South Asia,LKA,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,South Asia,NPL,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5
5,Afghanistan,South Asia,AFG,0.86,0.81,0.85,60,2.3,100,0,0.0,False,0.0,2.9,2026-04-04,43.0
6,China,East Asia,CHN,1.26,1.12,0.82,960,25.4,72,17840,10.2,False,0.0,990.0,2026-04-04,3.9
7,Japan,East Asia,JPN,1.15,1.04,1.20,3200,92.8,99,3520,3.5,True,8.2,182.0,2026-04-04,1.1
8,South Korea,East Asia,KOR,1.37,1.22,1.00,2800,68.1,97,3330,10.5,False,0.0,96.0,2026-04-04,1.5
9,Taiwan,East Asia,TWN,1.06,0.91,0.85,2200,69.2,98,1200,5.0,True,3.5,35.0,2026-04-04,1.4
10,Mongolia,East Asia,MNG,1.06,1.02,0.95,450,14.2,100,0,0.1,False,0.0,3.3,2026-04-04,7.1
11,Thailand,Southeast Asia,THA,1.24,1.10,0.78,580,15.6,62,1340,4.2,True,5.8,79.0,2026-04-04,6.4
12,Malaysia,Southeast Asia,MYS,0.46,0.86,0.50,820,59.4,35,770,2.8,True,14.2,56.0,2026-04-04,1.7
13,Indonesia,Southeast Asia,IDN,0.61,0.72,0.68,320,17.5,42,1080,0.5,True,18.5,148.0,2026-04-04,5.7
14,Vietnam,Southeast Asia,VNM,1.09,0.95,0.82,280,8.6,60,360,0.7,False,0.0,43.5,2026-04-04,11.7
15,Philippines,Southeast Asia,PHL,1.26,1.13,0.95,310,8.2,100,280,0.4,False,0.0,36.0,2026-04-04,12.2
16,Singapore,Southeast Asia,SGP,2.53,2.05,1.35,4800,63.2,100,1500,5.8,False,0.0,17.5,2026-04-04,1.6
17,Cambodia,Southeast Asia,KHM,1.27,1.17,1.02,180,4.7,100,0,0.0,False,0.0,4.8,2026-04-04,21.2
18,Myanmar,Southeast Asia,MMR,1.12,1.02,0.92,110,3.3,55,50,0.0,True,0.8,10.2,2026-04-04,30.5
19,Laos,Southeast Asia,LAO,1.32,1.16,1.08,160,4.0,100,0,0.0,False,0.0,2.4,2026-04-04,24.8
20,Brunei,Southeast Asia,BRN,0.39,0.23,0.30,2200,188.0,0,165,0.2,True,0.5,2.6,2026-04-04,0.5
21,Timor-Leste,Southeast Asia,TLS,1.38,1.32,1.15,120,2.9,100,0,0.0,False,0.0,0.4,2026-04-04,34.5

In [12]:
import requests

In [13]:
from io import StringIO

In [14]:
url = 'https://github.com/tokern/piicatcher/blob/master/tests/samples/sample-data.csv'

In [15]:
response = requests.get(url)

In [16]:
csv = StringIO(response.text)

In [17]:
df = pd.DataFrame(csv)

In [18]:
df.head()

    0
0  \n
1  \n
2  \n
3  \n
4  \n

In [ ]:
url = 'https://raw.githubusercontent.com/tokern/piicatcher/refs/heads/master/tests/samples/sample-data.csv'
df = pd.read_csv(url)

In [ ]:
df

,id,gender,birthdate,maiden_name,lname,fname,address,city,state,zip,phone,email,cc_type,cc_number,cc_cvc,cc_expiredate
0,172-32-1176,m,1958/04/21,Smith,White,Johnson,10932 Bigge Rd,Menlo Park,CA,94025,408 496-7223,jwhite@domain.com,m,5270 4267 6450 5516,123,2010/06/25
1,514-14-8905,f,1944/12/22,Amaker,Borden,Ashley,4469 Sherman Street,Goff,KS,66428,785-939-6046,aborden@domain.com,m,5370 4638 8881 3020,713,2011/02/01
2,213-46-8915,f,1958/04/21,Pinson,Green,Marjorie,309 63rd St. #411,Oakland,CA,94618,415 986-7020,mgreen@domain.com,v,4916 9766 5240 6147,258,2009/02/25
3,524-02-7657,m,1962/03/25,Hall,Munsch,Jerome,2183 Roy Alley,Centennial,CO,80112,303-901-6123,jmunsch@domain.com,m,5180 3807 3679 8221,612,2010/03/01
4,489-36-8350,m,1964/09/06,Porter,Aragon,Robert,3181 White Oak Drive,Kansas City,MO,66215,816-645-6936,raragon@domain.com,v,4929 3813 3266 4295,911,2011/12/01
5,514-30-2668,f,1986/05/27,Nicholson,Russell,Jacki,3097 Better Street,Kansas City,MO,66215,913-227-6106,jrussell@domain.com,a,345389698201044,232,2010/01/01
6,505-88-5714,f,1963/09/23,Mcclain,Venson,Lillian,539 Kyle Street,Wood River,NE,68883,308-583-8759,lvenson@domain.com,d,30204861594838,471,2011/12/01
7,690-05-5315,m,1969/10/02,Kings,Conley,Thomas,570 Nancy Street,Morrisville,NC,27560,919-656-6779,tconley@domain.com,v,4916 4811 5814 8111,731,2010/10/01
8,646-44-9061,M,1978/01/12,Kurtz,Jackson,Charles,1074 Small Street,New York,NY,10011,212-847-4915,cjackson@domain.com,m,5218 0144 2703 9266,892,2011/11/01
9,421-37-1396,f,1980/04/09,Linden,Davis,Susan,4222 Bedford Street,Jasper,AL,35501,205-221-9156,sdavis@domain.com,v,4916 4034 9269 8783,33,2011/04/01
10,461-97-5660,f,1975/01/04,Kingdon,Watson,Gail,3414 Gore Street,Houston,TX,77002,713-547-3414,gwatson@domain.com,v,4532 1753 6071 1112,694,2011/09/01
11,660-03-8360,f,1953/07/11,Onwunli,Garrison,Lisa,515 Hillside Drive,Lake Charles,LA,70629,337-965-2982,lgarrison@domain.com,v,4539 5385 7425 5825,680,2011/06/01
12,751-01-2327,f,1968/02/16,Simpson,Renfro,Julie,4032 Arron Smith Drive,Kaunakakai,HI,96748,808-560-1638,jrenfro@domain.com,m,5325 3256 9519 6624,238,2009/03/01
13,559-81-1301,m,1952/01/20,Mcafee,Heard,James,2865 Driftwood Road,San Jose,CA,95129,408-370-0031,jheard@domain.com,v,4532 4220 6922 9909,311,2010/09/01
14,624-84-9181,m,1980/01/16,Frazier,Reyes,Danny,3500 Diane Street,San Luis Obispo,CA,93401,805-369-0464,dreyes@domain.com,v,4532 0065 1968 5602,713,2009/11/01
15,449-48-3135,m,1982/06/14,Feusier,Hall,Mark,4986 Chapel Street,Houston,TX,77077,281-597-5517,mhall@domain.com,v,4556 0072 1294 7415,953,2010/05/01
16,477-36-0282,m,1961/03/10,Vasquez,Mceachern,Monte,456 Oral Lake Road,Minneapolis,MN,55401,952-412-3707,mmceachern@domain.com,m,5527 1247 5046 7780,889,2009/03/01
17,458-02-6124,m,1955/09/20,Pennebaker,Diaz,Christopher,582 Thrash Trail,Dallas,TX,75247,903-624-9156,cdiaz@domain.com,m,5299 1561 5689 1938,584,2011/08/01
18,044-34-6954,m,1967/05/28,Simpson,Lowe,Tim,1620 Maxwell Street,East Hartford,CT,6108,860-755-0293,tlowe@domain.com,m,5144 8691 2776 1108,616,2011/10/01
19,587-03-2682,f,1958/10/24,Dickerson,Oyola,Lynette,2489 O Conner Street,Pascagoula,MS,39567,228-938-2056,loyola@domain.com,v,4532 9929 3036 9308,991,2011/07/01
20,421-90-3440,f,1953/07/17,Kroeger,Morrison,Adriane,4696 Retreat Avenue,Birmingham,AL,35209,205-276-1807,amorrison@domain.com,v,4539 0031 3703 0728,322,2009/12/01
21,451-80-3526,m,1950/06/09,Parmer,Santos,Thomas,173 Lunetta Street,Fort Worth,TX,76104,940-859-1393,tsantos@domain.com,v,4716 6984 4983 6160,767,2011/09/01
22,300-62-3266,m,1965/02/10,Spain,Faulkner,Victor,1843 Olive Street,Toledo,OH,43602,419-340-3832,vfaulkner@domain.com,m,5548 0246 6336 5664,276,2010/02/01
23,322-84-2281,m,1977/08/19,Miley,Iorio,Albert,4899 University Hill Road,Springfield,IL,62701,217-615-6419,aiorio@domain.com,v,4916 6734 7572 5015,347,2010/02/01
24,465-73-5022,f,1964/06/20,Summers,Kaminski,Teresa,1517 Gambler Lane,Houston,TX,77006,281-906-2148,tkaminski@domain.com,m,5399 0706 4128 0178,721,2009/10/01
25,612-20-6832,m,1979/08/18,Banas,Edwards,Rick,4254 Walkers Ridge Way,Gardena,CA,90248,626-991-3620,redwards@domain.com,m,5293 8502 0071 3058,701,2010/08/01
26,687-05-8365,f,1976/05/24,Robbins,Peacock,Stacey,3396 Nancy Street,Raleigh,NC,27612,919-571-2339,speacock@domain.com,m,5495 8602 4508 6804,436,2011/02/01
27,205-52-0027,f,1950/03/26,Sanford,Nelson,Agnes,4213 High Meadow Lane,Avoca,PA,18641,570-480-8704,anelson@domain.com,m,5413 4428 0145 0036,496,2010/02/01
28,404-12-2154,f,1984/09/21,Garcia,Townsend,Mireille,2877 Glen Street,Paducah,KY,42003,270-408-7254,mtownsend@domain.com,v,4539 8219 0484 7598,710,2011/03/01
29,151-32-2558,f,1952/11/19,Stockdale,Zwick,Rebecca,784 Beechwood Avenue,Piscataway,NJ,8854,908-814-6733,rzwick@domain.com,v,5252 5971 4219 4116,173,2011/02/01

In [ ]:
df.head()

,id,gender,birthdate,maiden_name,lname,fname,address,city,state,zip,phone,email,cc_type,cc_number,cc_cvc,cc_expiredate
0,172-32-1176,m,1958/04/21,Smith,White,Johnson,10932 Bigge Rd,Menlo Park,CA,94025,408 496-7223,jwhite@domain.com,m,5270 4267 6450 5516,123,2010/06/25
1,514-14-8905,f,1944/12/22,Amaker,Borden,Ashley,4469 Sherman Street,Goff,KS,66428,785-939-6046,aborden@domain.com,m,5370 4638 8881 3020,713,2011/02/01
2,213-46-8915,f,1958/04/21,Pinson,Green,Marjorie,309 63rd St. #411,Oakland,CA,94618,415 986-7020,mgreen@domain.com,v,4916 9766 5240 6147,258,2009/02/25
3,524-02-7657,m,1962/03/25,Hall,Munsch,Jerome,2183 Roy Alley,Centennial,CO,80112,303-901-6123,jmunsch@domain.com,m,5180 3807 3679 8221,612,2010/03/01
4,489-36-8350,m,1964/09/06,Porter,Aragon,Robert,3181 White Oak Drive,Kansas City,MO,66215,816-645-6936,raragon@domain.com,v,4929 3813 3266 4295,911,2011/12/01